import type { ProductCategory } from '../../types/darktrainers';

export interface Product {
  id: string;
  name: string;
  subtitle?: string;
  brand: string;
  collab?: string;
  category: ProductCategory;
  colorway: string;
  price: number;
  memberPrice: number;
  isDropExclusive: boolean;
  releaseDate: string;
  sizes: number[];
  imageUrl: string;
  teaserImage?: string;
  description: string;
  tags: string[];
}

const B = 'DarkTrainers';

export const products: Product[] = [
  {
    id: 'volt-hi-ac26-magenta',
    name: 'VOLT-HI x AC26',
    subtitle: 'Magenta Drop',
    brand: B,
    collab: "AgentControl '26",
    category: 'lifestyle',
    colorway: 'Hot Pink / Neon Lime / White',
    price: 285,
    memberPrice: 245,
    isDropExclusive: true,
    releaseDate: '2026-05-26',
    sizes: [7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 12],
    imageUrl: '/images/products/volt-hi-ac26-magenta.webp',
    description:
      "AgentControl '26 pushes the VOLT-HI into a hot pink spotlight with neon lime accents and a crisp white base. Drop-exclusive and built to stand out.",
    tags: ['collab', 'limited', 'lifestyle', 'early-access'],
  },
  {
    id: 'volt-hi-ac26-purple-wave',
    name: 'VOLT-HI x AC26',
    subtitle: 'Purple Wave',
    brand: B,
    collab: "AgentControl '26",
    category: 'lifestyle',
    colorway: 'Electric Purple / Neon Lime / White',
    price: 285,
    memberPrice: 245,
    isDropExclusive: true,
    releaseDate: '2026-05-26',
    sizes: [7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 12],
    imageUrl: '/images/products/volt-hi-ac26-purple-wave.webp',
    description:
      "A purple-led VOLT-HI from the AgentControl '26 capsule with neon lime hits and a clean white counterbalance. Limited pairs, no standard release.",
    tags: ['collab', 'limited', 'lifestyle', 'early-access'],
  },
  {
    id: 'volt-hi-ac26-full-campaign',
    name: 'VOLT-HI x AC26',
    subtitle: 'Full Campaign',
    brand: B,
    collab: "AgentControl '26",
    category: 'lifestyle',
    colorway: 'Black / Pink / Purple / Neon Lime',
    price: 325,
    memberPrice: 279,
    isDropExclusive: true,
    releaseDate: '2026-05-26',
    sizes: [7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 12],
    imageUrl: '/images/products/volt-hi-ac26-full-campaign.webp',
    teaserImage: '/images/products/volt-hi-ac26-full-campaign.webp',
    description:
      "The loudest statement in the AgentControl '26 drop, layering the full black, pink, purple, and neon lime palette across the VOLT-HI silhouette.",
    tags: ['collab', 'limited', 'lifestyle', 'early-access'],
  },
  {
    id: 'apex-low-ac26-monstar',
    name: 'APEX LOW x AC26',
    subtitle: 'Monstar',
    brand: B,
    collab: "AgentControl '26",
    category: 'lifestyle',
    colorway: 'Black / White / Forest Green',
    price: 265,
    memberPrice: 225,
    isDropExclusive: true,
    releaseDate: '2026-05-26',
    sizes: [7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 12],
    imageUrl: '/images/products/apex-low-ac26-monstar.webp',
    description:
      "Monstar reworks the APEX LOW with a black and white base and forest green punch-through details. Part of the AgentControl '26 lifestyle drop.",
    tags: ['collab', 'limited', 'lifestyle', 'early-access'],
  },
  {
    id: 'apex-low-ac26-albert',
    name: 'APEX LOW x AC26',
    subtitle: 'Albert',
    brand: B,
    collab: "AgentControl '26",
    category: 'lifestyle',
    colorway: 'Black / Neon Lime / Pink / Purple',
    price: 265,
    memberPrice: 225,
    isDropExclusive: true,
    releaseDate: '2026-05-26',
    sizes: [7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 12],
    imageUrl: '/images/products/apex-low-ac26-albert.webp',
    description:
      "Albert brings the full AgentControl '26 energy to the APEX LOW with neon lime, pink, and purple against a black base, plus a dedicated splash teaser image.",
    tags: ['collab', 'limited', 'lifestyle', 'early-access'],
  },
  {
    id: 'phantom-hi-x-gravity-farms',
    name: 'DarkTrainers PHANTOM HI x Gravity Farms',
    brand: B,
    category: 'lifestyle',
    colorway: 'Cream / Forest / Gum',
    price: 220,
    memberPrice: 185,
    isDropExclusive: true,
    releaseDate: '2026-05-20',
    sizes: [7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 12],
    imageUrl: '/images/products/phantom-hi-x-gravity-farms.webp',
    description:
      'A one-time collab between DarkTrainers and Gravity Farms. Canvas upper, forest green toe cap, gum sole. 200 pairs. No restock.',
    tags: ['collab', 'limited', 'lifestyle', 'early-access'],
  },
  {
    id: 'volt-1',
    name: 'DarkTrainers VOLT-1',
    brand: B,
    category: 'running',
    colorway: 'Volt / Black / White',
    price: 185,
    memberPrice: 155,
    isDropExclusive: true,
    releaseDate: '2026-05-20',
    sizes: [7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 12],
    imageUrl: '/images/products/volt-1.webp',
    description:
      'Race-day energy return with a carbon-infused plate and volt hits for low-light visibility. Built for tempo days and race pace.',
    tags: ['Limited', 'Carbon plate', 'Early access'],
  },
  {
    id: 'apex-low',
    name: 'DarkTrainers APEX LOW',
    brand: B,
    category: 'lifestyle',
    colorway: 'Triple Black',
    price: 140,
    memberPrice: 119,
    isDropExclusive: false,
    releaseDate: '2026-04-01',
    sizes: [7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 12],
    imageUrl: '/images/products/apex-low.webp',
    description: 'Minimal court DNA with a sculpted midsole and premium leather upper. Your daily rotation, elevated.',
    tags: ['Daily', 'Leather'],
  },
  {
    id: 'circuit-mid',
    name: 'DarkTrainers CIRCUIT MID',
    brand: B,
    category: 'training',
    colorway: 'Cool Grey / Volt',
    price: 165,
    memberPrice: 138,
    isDropExclusive: false,
    releaseDate: '2026-03-10',
    sizes: [7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 12],
    imageUrl: '/images/products/circuit-mid.webp',
    description: 'Lockdown fit for lifts and agility drills. Mid-cut support without the bulk.',
    tags: ['Gym', 'Stability'],
  },
  {
    id: 'phantom-hi',
    name: 'DarkTrainers PHANTOM HI',
    brand: B,
    category: 'basketball',
    colorway: 'Black / Volt',
    price: 175,
    memberPrice: 148,
    isDropExclusive: false,
    releaseDate: '2026-02-14',
    sizes: [7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 12, 13],
    imageUrl: '/images/products/phantom-high.webp',
    description: 'Explosive first step, padded collar, outsole pattern tuned for hardwood grip.',
    tags: ['Hoops', 'Ankle support'],
  },
  {
    id: 'shadow-runner',
    name: 'DarkTrainers SHADOW RUNNER',
    brand: B,
    category: 'running',
    colorway: 'Charcoal / White',
    price: 155,
    memberPrice: 132,
    isDropExclusive: false,
    releaseDate: '2026-01-20',
    sizes: [7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 12],
    imageUrl: '/images/products/shadow-runner.webp',
    description: 'Daily miles with a breathable mesh upper and tuned cushioning for neutral gait.',
    tags: ['Road', 'Neutral'],
  },
  {
    id: 'gridlock',
    name: 'DarkTrainers GRIDLOCK',
    brand: B,
    category: 'lifestyle',
    colorway: 'White / Black',
    price: 130,
    memberPrice: 110,
    isDropExclusive: false,
    releaseDate: '2025-11-05',
    sizes: [7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 12],
    imageUrl: '/images/products/gridlock.webp',
    description: 'Technical overlays and a crisp white base — pairs with everything in your rotation.',
    tags: ['Classic', 'Unisex'],
  },
  {
    id: 'vault-proto',
    name: 'DarkTrainers VAULT PROTO',
    brand: B,
    category: 'basketball',
    colorway: 'Volt / Anthracite',
    price: 195,
    memberPrice: 165,
    isDropExclusive: true,
    releaseDate: '2026-06-01',
    sizes: [8, 8.5, 9, 9.5, 10, 10.5, 11, 12],
    imageUrl: '/images/products/vault-proto.webp',
    description: 'Prototype cushioning stack and translucent outsole. VIP early window before public drop.',
    tags: ['Prototype', 'VIP drop'],
  },
  {
    id: 'pulse-tr',
    name: 'DarkTrainers PULSE TR',
    brand: B,
    category: 'training',
    colorway: 'Black / Cool White',
    price: 145,
    memberPrice: 122,
    isDropExclusive: false,
    releaseDate: '2026-03-28',
    sizes: [7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 12],
    imageUrl: '/images/products/pulse-tr.webp',
    description: 'Versatile trainer for HIIT and short runs. Low-profile stability cage.',
    tags: ['HIIT', 'Versatile'],
  },
  {
    id: 'apex-low-x-control-freak',                    // kebab-case, matches image filename
    name: 'DarkTrainers Apex Low X Control Freak',
    brand: B,
    category: 'running',                   // running | basketball | lifestyle | training
    colorway: 'Black / Neon',
    price: 190,                            // standard price
    memberPrice: 165,                      // VIP price (~15-20% off)
    isDropExclusive: true,               // true = VIP early access only
    releaseDate: '2026-05-22',
    sizes: [7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 12],
    imageUrl: '/images/products/apex-low-x-control-freak.webp',
    description: 'I\'m about to lose control and I think I like it.  Tame the freak within with the new Control Freak Apex Low limited editiion drops.',
    tags: ['collab', 'limited', 'lifestyle', 'early-access']
  },
  // --- Footwear catalog expansion. Colorways and line extensions of the
  // silhouettes above, so each one reuses its silhouette's product image (the
  // same thing a real store does for a colorway variant). Tags are lowercase
  // here; the search ranking lowercases everything before matching, so the
  // older mixed-case tags above still match.
  //
  // These exist to give the three `search-ranking-algorithm` variations real
  // signal to sort on: overlapping keywords across name/description/tags, a
  // spread of prices, release dates from 2025 to late 2026, and a mix of
  // categories so `personalized-affinity` has a preferredCategory to favor. ---
  {
    id: 'volt-2-pacer',
    name: 'DarkTrainers VOLT-2 PACER',
    brand: B,
    category: 'running',
    colorway: 'Volt / Ink / Silver',
    price: 195,
    memberPrice: 165,
    isDropExclusive: false,
    releaseDate: '2026-07-14',
    sizes: [7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 12],
    imageUrl: '/images/products/volt-1.webp',
    description:
      'The VOLT line goes faster. A stiffer carbon plate and a lighter foam core built for race day and tempo intervals.',
    tags: ['running', 'carbon-plate', 'race-day', 'tempo'],
  },
  {
    id: 'shadow-runner-trail',
    name: 'DarkTrainers SHADOW RUNNER TRAIL',
    brand: B,
    category: 'running',
    colorway: 'Slate / Moss / Orange',
    price: 170,
    memberPrice: 145,
    isDropExclusive: false,
    releaseDate: '2026-06-18',
    sizes: [7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 12],
    imageUrl: '/images/products/shadow-runner.webp',
    description:
      'Trail build of the SHADOW RUNNER with an aggressive lug outsole, rock plate, and a water-resistant mesh upper for all-weather miles.',
    tags: ['running', 'trail', 'grip', 'all-weather'],
  },
  {
    id: 'shadow-runner-lite',
    name: 'DarkTrainers SHADOW RUNNER LITE',
    brand: B,
    category: 'running',
    colorway: 'Bone / Charcoal',
    price: 140,
    memberPrice: 119,
    isDropExclusive: false,
    releaseDate: '2026-02-02',
    sizes: [7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 12],
    imageUrl: '/images/products/shadow-runner.webp',
    description:
      'Stripped-back daily trainer for neutral runners. Same breathable mesh upper, less shoe underfoot, lighter on the wallet.',
    tags: ['running', 'lightweight', 'daily', 'neutral'],
  },
  {
    id: 'volt-1-eclipse',
    name: 'DarkTrainers VOLT-1',
    subtitle: 'Eclipse',
    brand: B,
    category: 'running',
    colorway: 'Black / Deep Volt',
    price: 185,
    memberPrice: 155,
    isDropExclusive: false,
    releaseDate: '2026-04-22',
    sizes: [7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 12],
    imageUrl: '/images/products/volt-1.webp',
    description:
      'Blacked-out VOLT-1 with the volt hits pulled back to the midsole edge. Carbon plate and race-day geometry unchanged.',
    tags: ['running', 'carbon-plate', 'limited'],
  },
  {
    id: 'shadow-tempo',
    name: 'DarkTrainers SHADOW TEMPO',
    brand: B,
    category: 'running',
    colorway: 'Graphite / Volt',
    price: 165,
    memberPrice: 140,
    isDropExclusive: false,
    releaseDate: '2026-05-08',
    sizes: [7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 12],
    imageUrl: '/images/products/shadow.webp',
    description:
      'Tempo-day trainer that sits between the daily SHADOW RUNNER and the race-day VOLT. Breathable, responsive, no plate.',
    tags: ['running', 'tempo', 'breathable'],
  },
  {
    id: 'volt-hydro',
    name: 'DarkTrainers VOLT HYDRO',
    brand: B,
    category: 'running',
    colorway: 'Storm Blue / Volt',
    price: 175,
    memberPrice: 148,
    isDropExclusive: false,
    releaseDate: '2026-08-05',
    sizes: [7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 12],
    imageUrl: '/images/products/volt-1.webp',
    description:
      'Waterproof membrane and a sealed collar for winter running. Reflective volt detailing for low-light visibility.',
    tags: ['running', 'waterproof', 'all-weather', 'winter'],
  },
  {
    id: 'phantom-hi-elite',
    name: 'DarkTrainers PHANTOM HI ELITE',
    brand: B,
    category: 'basketball',
    colorway: 'Black / Chrome / Volt',
    price: 205,
    memberPrice: 172,
    isDropExclusive: false,
    releaseDate: '2026-07-01',
    sizes: [7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 12, 13],
    imageUrl: '/images/products/phantom-high.webp',
    description:
      'Tournament build of the PHANTOM HI. Reinforced ankle support, a firmer heel counter, and an outsole pattern tuned for hardwood grip.',
    tags: ['basketball', 'ankle-support', 'hoops', 'court'],
  },
  {
    id: 'phantom-lo',
    name: 'DarkTrainers PHANTOM LO',
    brand: B,
    category: 'basketball',
    colorway: 'White / Volt',
    price: 160,
    memberPrice: 135,
    isDropExclusive: false,
    releaseDate: '2026-03-19',
    sizes: [7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 12, 13],
    imageUrl: '/images/products/phantom-high.webp',
    description:
      'Low-cut PHANTOM for guards who want the first step without the collar. Lighter, faster, same hardwood outsole.',
    tags: ['basketball', 'low-cut', 'court', 'guard'],
  },
  {
    id: 'vault-proto-ii',
    name: 'DarkTrainers VAULT PROTO II',
    brand: B,
    category: 'basketball',
    colorway: 'Translucent / Anthracite',
    price: 215,
    memberPrice: 180,
    isDropExclusive: true,
    releaseDate: '2026-08-20',
    sizes: [8, 8.5, 9, 9.5, 10, 10.5, 11, 12],
    imageUrl: '/images/products/vault-proto.webp',
    description:
      'Second-generation prototype cushioning stack with a fully translucent outsole. VIP early window before any public drop.',
    tags: ['basketball', 'prototype', 'limited', 'early-access'],
  },
  {
    id: 'vault-court-classic',
    name: 'DarkTrainers VAULT COURT CLASSIC',
    brand: B,
    category: 'basketball',
    colorway: 'Cream / Navy',
    price: 150,
    memberPrice: 128,
    isDropExclusive: false,
    releaseDate: '2025-12-01',
    sizes: [7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 12],
    imageUrl: '/images/products/vault-proto.webp',
    description:
      'Retro court silhouette in full-grain leather. Built off the original VAULT last, cut for everyday wear as much as hoops.',
    tags: ['basketball', 'retro', 'court', 'leather'],
  },
  {
    id: 'phantom-post',
    name: 'DarkTrainers PHANTOM POST',
    brand: B,
    category: 'basketball',
    colorway: 'Anthracite / Copper',
    price: 185,
    memberPrice: 157,
    isDropExclusive: false,
    releaseDate: '2026-06-05',
    sizes: [9, 9.5, 10, 10.5, 11, 12, 13],
    imageUrl: '/images/products/phantom-high.webp',
    description:
      'Maximum cushioning and a wide base for players who live in the post. Heavier than the ELITE on purpose.',
    tags: ['basketball', 'cushioning', 'hoops', 'support'],
  },
  {
    id: 'apex-low-sail',
    name: 'DarkTrainers APEX LOW',
    subtitle: 'Sail',
    brand: B,
    category: 'lifestyle',
    colorway: 'Sail / Gum',
    price: 145,
    memberPrice: 123,
    isDropExclusive: false,
    releaseDate: '2026-04-10',
    sizes: [7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 12],
    imageUrl: '/images/products/apex-low.webp',
    description:
      'The APEX LOW in off-white premium leather on a gum sole. Court DNA, sculpted midsole, daily rotation staple.',
    tags: ['lifestyle', 'daily', 'leather', 'neutral'],
  },
  {
    id: 'apex-mid-oxide',
    name: 'DarkTrainers APEX MID OXIDE',
    brand: B,
    category: 'lifestyle',
    colorway: 'Oxide Red / Bone',
    price: 158,
    memberPrice: 134,
    isDropExclusive: false,
    releaseDate: '2026-05-02',
    sizes: [7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 12],
    imageUrl: '/images/products/apex-low.webp',
    description:
      'Mid-cut APEX in oxide suede with a bone midsole. Same sculpted platform, a little more coverage.',
    tags: ['lifestyle', 'daily', 'suede'],
  },
  {
    id: 'gridlock-noir',
    name: 'DarkTrainers GRIDLOCK NOIR',
    brand: B,
    category: 'lifestyle',
    colorway: 'Triple Black',
    price: 135,
    memberPrice: 115,
    isDropExclusive: false,
    releaseDate: '2026-01-28',
    sizes: [7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 12],
    imageUrl: '/images/products/gridlock.webp',
    description:
      'The GRIDLOCK technical overlays rendered in all black. Unisex, everyday, pairs with everything.',
    tags: ['lifestyle', 'classic', 'unisex', 'everyday'],
  },
  {
    id: 'gridlock-court-canvas',
    name: 'DarkTrainers GRIDLOCK COURT CANVAS',
    brand: B,
    category: 'lifestyle',
    colorway: 'Natural Canvas / White',
    price: 120,
    memberPrice: 102,
    isDropExclusive: false,
    releaseDate: '2025-10-14',
    sizes: [7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 12],
    imageUrl: '/images/products/gridlock.webp',
    description:
      'Summer-weight GRIDLOCK in unbleached canvas. The entry price into the line and the lightest shoe in the catalog.',
    tags: ['lifestyle', 'canvas', 'classic', 'summer'],
  },
  {
    id: 'volt-hi-city',
    name: 'DarkTrainers VOLT-HI CITY',
    brand: B,
    category: 'lifestyle',
    colorway: 'Neon Lime / Off-White',
    price: 210,
    memberPrice: 178,
    isDropExclusive: false,
    releaseDate: '2026-06-26',
    sizes: [7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 12],
    imageUrl: '/images/products/volt-hi-ac26-magenta.webp',
    description:
      'A wearable take on the VOLT-HI high-top: the statement silhouette, the loud colorway dialed back to one neon lime panel.',
    tags: ['lifestyle', 'high-top', 'statement'],
  },
  {
    id: 'phantom-hi-heritage',
    name: 'DarkTrainers PHANTOM HI HERITAGE',
    brand: B,
    category: 'lifestyle',
    colorway: 'Cream / Forest / Gum',
    price: 195,
    memberPrice: 165,
    isDropExclusive: false,
    releaseDate: '2026-03-03',
    sizes: [7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 12],
    imageUrl: '/images/products/phantom-hi-x-gravity-farms.webp',
    description:
      'The PHANTOM HI pulled off the court and onto canvas, with a forest toe cap and a gum sole. General release, no drop window.',
    tags: ['lifestyle', 'heritage', 'gum-sole', 'canvas'],
  },
  {
    id: 'apex-low-ac26-sequel',
    name: 'APEX LOW x AC26',
    subtitle: 'Sequel',
    brand: B,
    collab: "AgentControl '26",
    category: 'lifestyle',
    colorway: 'Bone / Neon Lime / Purple',
    price: 275,
    memberPrice: 235,
    isDropExclusive: true,
    releaseDate: '2026-09-08',
    sizes: [7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 12],
    imageUrl: '/images/products/apex-low-ac26-monstar.webp',
    description:
      "The closing chapter of the AgentControl '26 capsule: a bone APEX LOW with neon lime and purple carried over from the Albert colorway.",
    tags: ['collab', 'limited', 'lifestyle', 'early-access'],
  },
  {
    id: 'circuit-mid-pro',
    name: 'DarkTrainers CIRCUIT MID PRO',
    brand: B,
    category: 'training',
    colorway: 'Cool Grey / Black',
    price: 180,
    memberPrice: 152,
    isDropExclusive: false,
    releaseDate: '2026-07-22',
    sizes: [7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 12],
    imageUrl: '/images/products/circuit-mid.webp',
    description:
      'Flat, dense midsole for heavy lifting plus the CIRCUIT lockdown fit for agility drills. The gym shoe that does both.',
    tags: ['training', 'gym', 'stability', 'lifting'],
  },
  {
    id: 'circuit-low-flex',
    name: 'DarkTrainers CIRCUIT LOW FLEX',
    brand: B,
    category: 'training',
    colorway: 'Volt / White',
    price: 138,
    memberPrice: 117,
    isDropExclusive: false,
    releaseDate: '2026-02-25',
    sizes: [7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 12],
    imageUrl: '/images/products/circuit-mid.webp',
    description:
      'Low-cut CIRCUIT with a segmented forefoot for HIIT and class work. Flexible where the MID is locked down.',
    tags: ['training', 'gym', 'flexible', 'hiit'],
  },
  {
    id: 'pulse-tr-2',
    name: 'DarkTrainers PULSE TR 2',
    brand: B,
    category: 'training',
    colorway: 'Black / Volt',
    price: 155,
    memberPrice: 131,
    isDropExclusive: false,
    releaseDate: '2026-06-11',
    sizes: [7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 12],
    imageUrl: '/images/products/pulse-tr.webp',
    description:
      'Second generation of the versatile PULSE trainer. Wider stability cage, more forefoot cushioning for short runs between sets.',
    tags: ['training', 'hiit', 'versatile', 'cross-training'],
  },
  {
    id: 'pulse-tr-studio',
    name: 'DarkTrainers PULSE TR STUDIO',
    brand: B,
    category: 'training',
    colorway: 'Bone / Cool White',
    price: 130,
    memberPrice: 110,
    isDropExclusive: false,
    releaseDate: '2026-01-09',
    sizes: [7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 12],
    imageUrl: '/images/products/pulse-tr.webp',
    description:
      'Indoor studio trainer with a pivot-friendly outsole and a lightweight knit upper. Built for mat and bike work, not the road.',
    tags: ['training', 'studio', 'lightweight', 'indoor'],
  },
  {
    id: 'circuit-strap',
    name: 'DarkTrainers CIRCUIT STRAP',
    brand: B,
    category: 'training',
    colorway: 'Anthracite / Volt',
    price: 172,
    memberPrice: 146,
    isDropExclusive: false,
    releaseDate: '2026-08-14',
    sizes: [7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 12],
    imageUrl: '/images/products/circuit-mid.webp',
    description:
      'Midfoot strap over the CIRCUIT platform for squats and cleans. Maximum lockdown, minimum heel lift.',
    tags: ['training', 'lifting', 'strap', 'stability'],
  },
  {
    id: 'pulse-trail-tr',
    name: 'DarkTrainers PULSE TRAIL TR',
    brand: B,
    category: 'training',
    colorway: 'Moss / Bone',
    price: 168,
    memberPrice: 142,
    isDropExclusive: false,
    releaseDate: '2026-05-16',
    sizes: [7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 12],
    imageUrl: '/images/products/pulse-tr.webp',
    description:
      'Outdoor cross-training build with a lugged outsole and a reinforced toe. For sled work, hill sprints, and grip on wet ground.',
    tags: ['training', 'outdoor', 'trail', 'grip'],
  },
  // --- Collectibles line (figures, plush, trading cards). No sizes; generic IP-free names. ---
  {
    id: 'toggle-figure-volt',
    name: 'Toggle Figure – Volt',
    brand: B,
    category: 'collectibles',
    colorway: 'Holographic Foil',
    price: 34.99,
    memberPrice: 29.99,
    isDropExclusive: false,
    releaseDate: '2025-01-01',
    sizes: [],
    imageUrl: '/images/collectibles/toggle-figure-volt.jpg',
    description: 'Limited-run die-cast figure with holographic foil finish.',
    tags: ['collectible', 'figure'],
  },
  {
    id: 'toggle-figure-matte-black',
    name: 'Toggle Figure – Matte Black',
    brand: B,
    category: 'collectibles',
    colorway: 'Matte Black / Volt',
    price: 29.99,
    memberPrice: 25.49,
    isDropExclusive: false,
    releaseDate: '2025-02-01',
    sizes: [],
    imageUrl: '/images/collectibles/toggle-figure-matte-black.jpg',
    description: 'Stylized vinyl figure with a matte black body and volt accent detailing.',
    tags: ['collectible', 'figure'],
  },
  {
    id: 'toggle-figure-glow',
    name: 'Toggle Figure – Glow Edition',
    brand: B,
    category: 'collectibles',
    colorway: 'Phosphor Green',
    price: 39.99,
    memberPrice: 33.99,
    isDropExclusive: false,
    releaseDate: '2025-03-01',
    sizes: [],
    imageUrl: '/images/collectibles/toggle-figure-glow.jpg',
    description: 'Hand-finished figure cast in phosphor resin that glows after dark.',
    tags: ['collectible', 'figure'],
  },
  {
    id: 'toggle-beanie-baby',
    name: 'Toggle Beanie Plush',
    brand: B,
    category: 'collectibles',
    colorway: 'Volt / Charcoal',
    price: 24.99,
    memberPrice: 21.24,
    isDropExclusive: false,
    releaseDate: '2025-01-15',
    sizes: [],
    imageUrl: '/images/collectibles/toggle-beanie-baby.jpg',
    description: 'Soft embroidered mascot plush in the signature volt colorway.',
    tags: ['collectible', 'plush'],
  },
  {
    id: 'togglemon-card-special',
    name: 'Togglemon Special Edition Card',
    brand: B,
    category: 'collectibles',
    colorway: 'Holographic',
    price: 24.99,
    memberPrice: 21.24,
    isDropExclusive: false,
    releaseDate: '2025-02-15',
    sizes: [],
    imageUrl: '/images/collectibles/togglemon-card-special.jpg',
    description: 'Rare special edition holographic card featuring the original Togglemon mascot.',
    tags: ['collectible', 'trading-cards'],
  },
  {
    id: 'jumbo-mascot-plush',
    name: 'Jumbo Mascot Plush',
    brand: B,
    category: 'collectibles',
    colorway: 'Cream / Forest',
    price: 49.99,
    memberPrice: 42.49,
    isDropExclusive: false,
    releaseDate: '2025-04-01',
    sizes: [],
    imageUrl: '/images/collectibles/jumbo-mascot-plush.jpg',
    description: 'Oversized premium plush with weighted base and stitched detailing.',
    tags: ['collectible', 'plush'],
  },
  {
    id: 'togglemon-cardpack',
    name: 'Togglemon Card Pack',
    brand: B,
    category: 'collectibles',
    colorway: 'Assorted',
    price: 9.99,
    memberPrice: 8.49,
    isDropExclusive: false,
    releaseDate: '2025-01-10',
    sizes: [],
    imageUrl: '/images/collectibles/togglemon-cardpack.jpg',
    description: 'Sealed pack of base-set trading cards with one guaranteed foil insert.',
    tags: ['collectible', 'trading-cards'],
  },
  {
    id: 'togglemon-holopack',
    name: 'Togglemon Holo Pack',
    brand: B,
    category: 'collectibles',
    colorway: 'Holographic',
    price: 14.99,
    memberPrice: 12.74,
    isDropExclusive: false,
    releaseDate: '2025-03-10',
    sizes: [],
    imageUrl: '/images/collectibles/togglemon-holopack.jpg',
    description: 'Premium holo-edition card pack with two guaranteed holographic cards.',
    tags: ['collectible', 'trading-cards'],
  },
  {
    id: 'aibert-figure-matte-blue',
    name: 'Aibert Figure – Matte Blue',
    brand: 'AgentControl',
    category: 'collectibles',
    colorway: 'Matte Blue',
    price: 29.99,
    memberPrice: 24.99,
    isDropExclusive: false,
    releaseDate: '2025-06-01',
    sizes: [],
    imageUrl: '/images/collectibles/aibert-figure-matte-blue.jpg',
    description: 'Matte blue vinyl figure from the AgentControl universe.',
    tags: ['collectible', 'figure'],
  },
  {
    id: 'aibert-figure-sk8ter',
    name: 'Aibert Figure – Sk8ter Edition',
    brand: 'AgentControl',
    category: 'collectibles',
    colorway: 'Sk8ter',
    price: 34.99,
    memberPrice: 29.99,
    isDropExclusive: false,
    releaseDate: '2025-06-01',
    sizes: [],
    imageUrl: '/images/collectibles/aibert-figure-sk8ter.jpg',
    description: 'Limited Sk8ter Edition Aibert figure from the AgentControl universe.',
    tags: ['collectible', 'figure'],
  },
  {
    id: 'jumbo-aibert-plush',
    name: 'Jumbo Aibert Plush',
    brand: 'AgentControl',
    category: 'collectibles',
    colorway: 'Classic',
    price: 44.99,
    memberPrice: 37.99,
    isDropExclusive: false,
    releaseDate: '2025-06-01',
    sizes: [],
    imageUrl: '/images/collectibles/jumbo-aibert-plush.jpg',
    description: 'Oversized soft plush featuring Aibert from the AgentControl universe.',
    tags: ['collectible', 'plush'],
  },
  {
    id: 'agentcontrol-comic-issue1',
    name: 'AgentControl Comic – Issue 1',
    brand: 'AgentControl',
    category: 'collectibles',
    colorway: 'Print',
    price: 14.99,
    memberPrice: 11.99,
    isDropExclusive: false,
    releaseDate: '2025-06-01',
    sizes: [],
    imageUrl: '/images/collectibles/agentcontrol-comic-issue1.jpg',
    description: 'First issue of the AgentControl comic series. Collectible edition.',
    tags: ['collectible', 'comic'],
  },
  {
    id: 'togglemon-holopack-agentcontrol',
    name: 'Togglemon Holo Pack – AgentControl Edition',
    brand: 'Togglemon',
    category: 'collectibles',
    colorway: 'Holographic',
    price: 24.99,
    memberPrice: 19.99,
    isDropExclusive: false,
    releaseDate: '2025-06-01',
    sizes: [],
    imageUrl: '/images/collectibles/togglemon-holopack-agentcontrol.jpg',
    description: 'Special AgentControl crossover edition Togglemon holographic card pack.',
    tags: ['collectible', 'trading-cards'],
  },
  {
    id: 'codecontrol-comic-issue1',
    name: 'CodeControl Comic – Issue 1',
    brand: 'CodeControl',
    category: 'collectibles',
    colorway: 'Print',
    price: 12.99,
    memberPrice: 9.99,
    isDropExclusive: false,
    releaseDate: '2025-05-01',
    sizes: [],
    imageUrl: '/images/collectibles/codecontrol-comic-issue1.jpg',
    description:
      'First issue of the CodeControl comic series. The helmeted hero battles bugs, seg-faults, and rogue patches. Toggle Comics.',
    tags: ['collectible', 'comic'],
  },
  {
    id: 'codecontrol-crackdown-game',
    name: 'CodeControl: Crackdown – Retro Game',
    brand: 'CodeControl',
    category: 'collectibles',
    colorway: 'Pixel Art',
    price: 19.99,
    memberPrice: 15.99,
    isDropExclusive: false,
    releaseDate: '2025-05-01',
    sizes: [],
    imageUrl: '/images/collectibles/codecontrol-crackdown-game.jpg',
    description:
      'Retro pixel-art game from Toggle. Battle insect enemies through Data City Core as the CodeControl hero.',
    tags: ['collectible', 'game'],
  },
  {
    id: 'codecontrol-unisex-shirt',
    name: 'CodeControl Issue #1 Tee – Unisex',
    brand: 'CodeControl',
    category: 'collectibles',
    colorway: 'Black',
    price: 34.99,
    memberPrice: 27.99,
    isDropExclusive: false,
    releaseDate: '2025-05-01',
    sizes: [],
    imageUrl: '/images/collectibles/codecontrol-unisex-shirt.jpg',
    description: 'Unisex black tee printed with the CodeControl Issue #1 comic cover. By Toggle.',
    tags: ['collectible', 'apparel'],
  }
];

export function getProductById(id: string): Product | undefined {
  return products.find((p) => p.id === id);
}
